/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminModelRouteImport } from './routes/admin/model'
import { Route as TestsTestIdRouteImport } from './routes/tests.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelRoute = AdminModelRouteImport.update({
  id: '/admin/model',
  path: '/admin/model',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestIdRoute = TestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/settings': typeof SettingsRoute
  '/admin/model': typeof AdminModelRoute
  '/tests/$testId': typeof TestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/settings': typeof SettingsRoute
  '/admin/model': typeof AdminModelRoute
  '/tests/$testId': typeof TestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/settings': typeof SettingsRoute
  '/admin/model': typeof AdminModelRoute
  '/tests/$testId': typeof TestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clusters' | '/settings' | '/admin/model' | '/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clusters' | '/settings' | '/admin/model' | '/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/clusters'
    | '/settings'
    | '/admin/model'
    | '/tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClustersRoute: typeof ClustersRoute
  SettingsRoute: typeof SettingsRoute
  AdminModelRoute: typeof AdminModelRoute
  TestsTestIdRoute: typeof TestsTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/model': {
      id: '/admin/model'
      path: '/admin/model'
      fullPath: '/admin/model'
      preLoaderRoute: typeof AdminModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testId': {
      id: '/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof TestsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClustersRoute: ClustersRoute,
  SettingsRoute: SettingsRoute,
  AdminModelRoute: AdminModelRoute,
  TestsTestIdRoute: TestsTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
